version: '3.8'

services:
  stirling-pdf:
    image: ghcr.io/aaacoder-ds/stirling-pdf:latest
    container_name: stirling-pdf
    ports:
      - "3082:8080"
    volumes:
      - /mnt/sdb/PDFTools/trainingData:/usr/share/tessdata
      - /mnt/sdb/PDFTools/extraConfigs:/configs
      - /mnt/sdb/PDFTools/customFiles:/customFiles
      - /mnt/sdb/PDFTools/logs:/logs
      - /mnt/sdb/PDFTools/pipeline:/pipeline
      - ./scripts/init-dokploy.sh:/scripts/init-dokploy.sh
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_US
      - SYSTEM_DEFAULTLOCALE=en-US
      - SYSTEM_MAXFILESIZE=100
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_CUSTOM_OPTS=-Dserver.address=0.0.0.0 -Dserver.port=8080 -Dserver.bind-address=0.0.0.0 -Dspring.main.web-application-type=servlet
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8080
      - SYSTEM_CLEANUP_ENABLED=true
      - SYSTEM_CLEANUP_INTERVAL=300
      - SYSTEM_CLEANUP_MAXAGE=3600
      - SYSTEM_CLEANUP_MAXSIZE=26843545600
      - POSTHOG_API_KEY=dummy-key-for-docker
      - POSTHOG_HOST=https://eu.i.posthog.com
      - POSTHOG_ENABLED=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirling-pdf.rule=Host(`pdftools.aaacoder.xyz`)"
      - "traefik.http.routers.stirling-pdf.entrypoints=websecure"
      - "traefik.http.routers.stirling-pdf.tls.certresolver=letsencrypt"
      - "traefik.http.services.stirling-pdf.loadbalancer.server.port=8080"
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
