server:
  address: 0.0.0.0
  port: 8080
  bind-address: 0.0.0.0

spring:
  main:
    web-application-type: servlet
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Additional server configuration
server:
  tomcat:
    accept-count: 100
    max-connections: 8192
    threads:
      max: 200
      min-spare: 10

# Force binding to all interfaces
server:
  address: 0.0.0.0
  port: 8080 